AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # TerraformStateBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: terraform-state-bucket-arqi # Ensure uniqueness
  #     VersioningConfiguration:
  #       Status: Enabled

  # TerraformLockTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: terraform-lock-arqi
  #     AttributeDefinitions:
  #       - AttributeName: LockID
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: LockID
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST

  # TerraformSSMParameter:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Name: dynamic_string-arqi
  #     Type: String
  #     Value: "Hello from SSM!"
  #     Description: "Dynamic string stored in SSM Parameter Store"

  # TerraformIAMRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: TerraformServiceRole-arqi
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: [ec2.amazonaws.com]
  #           Action: sts:AssumeRole
  #     Policies:
  #       - PolicyName: TerraformFullAccess
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Action: ["s3:*", "dynamodb:*", "ssm:*"]
  #               Effect: Allow
  #               Resource: "*"
  TerraformInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    # DependsOn: TerraformIAMRole
    Properties:
      InstanceProfileName: TerraformInstanceProfile-arqi
      Roles: 
        - TerraformServiceRole-arqi
  
  
  
  JenkinsServer:
    Type: AWS::EC2::Instance
    DependsOn: TerraformInstanceProfile
    Properties:
      InstanceType: t2.medium
      ImageId: ami-003c3655bc8e97ae1 # Update as per your region
      KeyName: new-key-pair
      SecurityGroupIds:
        - sg-0370218280017bc97
      IamInstanceProfile: !Ref TerraformInstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt update -y
          apt install -y openjdk-11-jdk wget
          wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
          apt update -y
          apt install -y jenkins
          systemctl enable jenkins
          systemctl start jenkins
      Tags:
        - Key: Name
          Value: JenkinsServer

  # JenkinsSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Enable HTTP and SSH access for Jenkins
  #     VpcId: vpc-0b74b938c4056ab9b # Update with your VPC ID
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 8080
  #         ToPort: 8080
  #         CidrIp: 0.0.0.0/0

# Outputs:
  # BucketName:
  #   Description: "The name of the S3 bucket created for Terraform state."
  #   Value: !Ref TerraformStateBucket

  # DynamoDBTableName:
  #   Description: "The name of the DynamoDB table used for Terraform lock."
  #   Value: !Ref TerraformLockTable

  # SSMParameterName:
  #   Description: "The name of the SSM parameter created for dynamic string."
  #   Value: !Ref TerraformSSMParameter

  # IAMRoleName:
  #   Description: "The name of the IAM role created for Terraform."
  #   Value: !Ref TerraformIAMRole

  # JenkinsServerPublicIP:
  #   Description: "The public IP of the Jenkins server."
  #   Value: !GetAtt JenkinsServer.PublicIp
